export const START_DOG_BREEDS_LOADING = 'START_DOG_BREEDS_LOADING';
export const DOG_BREEDS_LOADED = 'DOG_BREEDS_LOADED';
export const STOP_DOG_BREEDS_LOADING = 'STOP_DOG_BREEDS_LOADING';
export const ERROR_DOG_BREEDS_LOADING = 'ERROR_DOG_BREEDS_LOADING'
