export const START_CAT_BREEDS_LOADING = 'START_CAT_BREEDS_LOADING';
export const CAT_BREEDS_LOADED = 'CAT_BREEDS_LOADED';
export const STOP_CAT_BREEDS_LOADING = 'STOP_CAT_BREEDS_LOADING';
export const ERROR_CAT_BREEDS_LOADING = 'ERROR_CAT_BREEDS_LOADING';
